app/main/blueprint_core.py
# from flask-socketio-chat:
# from flask import session, redirect, url_for, render_template, request
# from web-ctrl:
# from flask import Flask, render_template, Response, request, redirect, url_for, Markup, send_from_directory

from flask import render_template, request, Markup, send_from_directory, Blueprint, current_app #, url_for
import json
import os.path

# print(f"blueprint_core_name={__name__}") = app.main.blueprint_core
blueprint_core = Blueprint('blueprint_core', __name__)

from app.main.defines import *
from app.func_base import send_stop_to_base, send_settings_to_base

import sys
sys.path.append(f'{user_dir}/{repos_dir}/control_ipc_utils')
try:
   from control_ipc_defines import *
except:
   current_app.logger.error("Problems with 'control_ipc' modules, please run: git clone https://github.com/davidcjordan/control_ipc_utils")
   exit()


def read_display_customization_file():
   try:
      with open(f'{settings_dir}/ui_customization.json') as f:
         customization_dict = json.load(f)
   except:
      customization_dict = {"title": "", "icon": "/static/favicon.ico"}
   return customization_dict

def read_base_settings_from_file():
   try:
      with open(f'{settings_dir}/{settings_filename}') as f:
         settings_dict = json.load(f)
         # current_app.logger.debug(f"Settings restored: {settings_dict}")
   except:
      current_app.logger.warning(f"Read of '{settings_dir}/{settings_filename}' failed; using defaults.")
      settings_dict = {GRUNTS_PARAM: 0, TRASHT_PARAM: 0, LEVEL_PARAM: LEVEL_DEFAULT, \
            SERVE_MODE_PARAM: 1, TIEBREAKER_PARAM: 0, \
            SPEED_MOD_PARAM: SPEED_MOD_DEFAULT, DELAY_MOD_PARAM: DELAY_MOD_DEFAULT, \
            ELEVATION_MOD_PARAM: ELEVATION_ANGLE_MOD_DEFAULT,
            CONTINUOUS_MOD_PARAM: 0, ADVANCED_GAME_PARAM: 0}
   # !! need to add defaults to new settings as they are added:
   if CONTINUOUS_MOD_PARAM not in settings_dict:
      settings_dict[CONTINUOUS_MOD_PARAM] = 0
   if ADVANCED_GAME_PARAM not in settings_dict:
      settings_dict[ADVANCED_GAME_PARAM] = 0
   return settings_dict

display_customization_dict = read_display_customization_file()
base_settings_dict = read_base_settings_from_file()


@blueprint_core.route('/favicon.ico')
def favicon():
   from os import path 
   return send_from_directory(path.join(current_app.root_path, 'static'),
                               'favicon.ico', mimetype='image/vnd.microsoft.icon')


@blueprint_core.route(MAIN_URL, methods=DEFAULT_METHODS)
def index():

   # current_app.logger.debug(f"Test of printing function name: in function: {sys._getframe(0).f_code.co_name}")

   # clicking stop on the game_url & drill_url goes to main/home/index, so issue stop.
   send_stop_to_base()

   # clear the previous drill id ; there wasn't a central place to clear it in blueprint_drills.py
   set_previous_drill_id(None)

   global display_customization_dict 
   # get an unbound error if customization_dict is not declared global
   if 'icon' not in display_customization_dict:
      current_app.logger.debug("reading in customization_dict")
      display_customization_dict = read_display_customization_file()

   global base_settings_dict 
   if GRUNTS_PARAM not in base_settings_dict:
      base_settings_dict = read_base_settings_from_file()
   # updating the base settings (drill/game) occurs at game/drill start:
   # send settings to base also happens here (index) so that the settings are updated when the base is restarted
   send_settings_to_base(base_settings_dict)
   current_app.logger.info("sent base settings to base")

   # example of setting button disabled and a button ID
   # TODO: fix disable CSS
   # onclick_choices = [{"value": button_label, "onclick_url": MAIN_URL, "disabled": 1, "id": "Done"}], \

   onclick_choice_list = [\
      {"html_before": "Game:", "value": "Play", "onclick_url": GAME_URL, "id": "game_button"},\
      {"value": "Settings", "onclick_url": GAME_OPTIONS_URL, "id": "game_settings", "html_after": html_horizontal_rule},\
      # {"value": "Help", "id": "game_help_button", "html_after": html_horizontal_rule},\
      {"html_before": "Drill:", "value": "Recents", "onclick_url": RECENTS_URL},\
      {"value": "Select", "onclick_url": DRILL_LIST_URL, "html_after": html_horizontal_rule},\
      {"value": "Workouts", "onclick_url": SELECT_WORKOUT_URL, "html_after": html_horizontal_rule}, \
      {"value": "Settings", "onclick_url": SETTINGS_URL}
   ]

   # page_js = [Markup('<script src="/static/js/game_help.js" defer></script>')]

   # added try/except because sometimes the display_custom_dict seems to be missing - this is a workaround to avoid a web server fault
   try:
      this_template = render_template(CHOICE_INPUTS_TEMPLATE, \
         page_title = "Welcome to Boomer", \
         installation_icon = display_customization_dict['icon'], \
         onclick_choices = onclick_choice_list, \
         # page_specific_js = page_js, \
         footer_center = display_customization_dict['title'])
   except:
      this_template = render_template(CHOICE_INPUTS_TEMPLATE, \
         page_title = "Welcome to Boomer", \
         onclick_choices = onclick_choice_list)
      
   return this_template


@blueprint_core.route(FAULTS_URL, methods=DEFAULT_METHODS)
def faults():
   if 'icon' not in display_customization_dict:
      read_display_customization_file()

   return render_template(FAULTS_TEMPLATE, \
      page_title = "Problems Detected")
      # installation_icon = display_customization_dict['icon'], \
      # footer_center = display_customization_dict['title'])


@blueprint_core.route(SETTINGS_URL, methods=DEFAULT_METHODS)
def settings():

   # value is the label of the button
   onclick_choice_list = [\
      {"html_before": "Check:", \
         "value": "Cameras", "onclick_url": CAM_VERIF_URL, "html_after": html_horizontal_rule}, \
      {"html_before": "Calibrate:", \
         "value": "Thrower", "onclick_url": THROWER_CALIB_SELECTION_URL}, \
      {"value": "Left Camera", "onclick_url": CAM_LOCATION_URL, "param_name": CAM_SIDE_ID, "param_value": CAM_SIDE_LEFT_LABEL}, \
      {"value": "Right Cam", "onclick_url": CAM_LOCATION_URL, "param_name": CAM_SIDE_ID, "param_value": CAM_SIDE_RIGHT_LABEL, \
         "html_after": html_horizontal_rule}
   ]

   settings_radio_options = [\
   {'name': GRUNTS_PARAM, 'legend':"Grunts", 'buttons':[ \
      {'label': "Off", 'value': 0}, \
      {'label': "On", 'value': 1}, \
   ]}, \
   {'name': TRASHT_PARAM,'legend':"Trash Talking", 'buttons':[ \
      {'label': "Off", 'value': 0}, \
      {'label': "On", 'value': 1}, \
   ]} \
   ]

   # intermittently, the code will get here without the reading the base_settings being loaded.
   # so the following are defensive, in addition to the try/except around the 'checked' statements
   if GRUNTS_PARAM not in base_settings_dict or ELEVATION_MOD_PARAM not in base_settings_dict:
      current_app.logger.warning(f"GRUNTS_PARAM not in base_settings_dict; re-reading base_settings")
      read_base_settings_from_file()

   if GRUNTS_PARAM not in base_settings_dict:
      current_app.logger.error(f"GRUNTS_PARAM not in base_settings_dict AFTER re-reading base_settings")

   try:
      settings_radio_options[0]['buttons'][base_settings_dict[GRUNTS_PARAM]]['checked'] = 1
      settings_radio_options[1]['buttons'][base_settings_dict[TRASHT_PARAM]]['checked'] = 1
   except:
      pass
   
   page_js = [Markup('<script src="/static/js/radio-button-emit.js" defer></script>')]

   return render_template(CHOICE_INPUTS_TEMPLATE, \
      home_button = my_home_button, \
      page_title = "Change Settings or Perform Calibration", \
      installation_icon = display_customization_dict['icon'], \
      onclick_choices = onclick_choice_list, \
      radio_options = settings_radio_options, \
      page_specific_js = page_js, \
      footer_center = display_customization_dict['title'])


@blueprint_core.route(DONE_URL, methods=DEFAULT_METHODS)
def done():

   # from app.func_base import previous_drill_id
   global previous_drill_id

   send_stop_to_base()

   this_page_title = "Finished"
   onclick_choice_list = [{"value": "OK", "onclick_url": MAIN_URL}]

   if previous_drill_id is not None:
      onclick_choice_list.append({"value": "Repeat", "onclick_url": DRILL_URL, \
                                  "param_name": "drill_id", "param_value": previous_drill_id})
      this_page_title += f" Drill #{previous_drill_id}"
   else:
      current_app.logger.info(f"previous_drill_id is None")

   return render_template(CHOICE_INPUTS_TEMPLATE, \
      page_title = this_page_title, \
      installation_icon = display_customization_dict['icon'], \
      onclick_choices = onclick_choice_list, \
      footer_center = display_customization_dict['title'])
      
@blueprint_core.route(WORKOUT_RESULT_URL, methods=DEFAULT_METHODS)
def workout_result_screen():
   if 'icon' not in display_customization_dict:
      read_display_customization_file()

   return render_template(WORKOUT_RESULT_TEMPLATE, \
      home_button = my_home_button, \
      page_title = "Workout Results")

def write_base_settings_to_file():
   try:
      with open(f'{settings_dir}/{settings_filename}', 'w') as f:
            json.dump(base_settings_dict, f)
         # current_app.logger.debug(f"Settings written: {settings_dict}")
   except:
      current_app.logger.error(f"Settings file write failed.")


previous_drill_id = None
# using a function instead of importing the variable from blueprint_drills
# because the calibration_value did not appear to written by the event handler
def set_previous_drill_id(value):
   global previous_drill_id
   previous_id = previous_drill_id
   previous_drill_id = value
   current_app.logger.info(f'Change calibration_value: previous={previous_id} new={previous_drill_id}')

@blueprint_core.route('/save_wifi', methods=['POST'])
def save_wifi():
    # 1. Capture the data
    ssid = request.form.get('ssid')
    password = request.form.get('password')

app/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
  {# refer to https://jinja.palletsprojects.com/en/3.0.x/templates/# for info on jinja templates
      the minus sign after the <% below keeps ninja2 from emitting a newline
  #}
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Boomer-Control</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/boomer.css') }}">
    {%- block page_specific_styles %} 
      {%- for line in page_specific_styles %}
        {{line}}
      {%- endfor %}
    {%- endblock %} 
    <script src="/static/js/socket.io.js" defer></script>
    <script src="/static/js/state_update.js" defer></script>
    {%- block page_specific_js %} 
      {%- for line in page_specific_js %}
        {{line}}
      {%- endfor %}
    {%- endblock %} 
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div class="header-icon">
          {{ home_button }}
        </div>
        <div class="header-h1">
          <p>{{ page_title }}</p>
        </div>
        <div class="header-icon">
          <img src="{{ installation_icon }}" style="height:64px;">
        </div>
      </div>     
      <div class="section">
      {{ message }}
        {%- block stats %}
        {%- endblock %}
        {%- block selections %}
        {%- endblock %}
        {%- block control %}
        {%- endblock %}
      </div>
      <div class="footer"> 
        <div class="footer-left" id="base_state">Status: Idle</div>
        <div class="footer-center" id="mode">{{ footer_center }}</div>
        <div class="footer-right" id="company">© tennisrobot.com</div>
      </div>
    </div>
  </body>
</html>

app/templates/layouts/cam_calib.html
{% extends "layouts/base.html" %}

{%- block selections %}
<div class="img-zoom-container">
  <div id="div_not_zoomed" class="div_not_zoomed_class">
    <canvas id="canvas_not_zoomed"></canvas>
  </div>
  <div id="div_zoomed_8" class="div_zoomed_8_class">
    <canvas id="canvas_id_zoomed_8"></canvas>
  </div>
  <div id="div_submit_form" class="calibration_controls">
    <form id="court_coordinates" action="/cam_calib_done" method="POST">
      {%- for coord, value in court_point_coords.items() %}
      <input type="hidden" id="{{coord}}X" name="{{coord}}X" value={{value[0]}}>
      <input type="hidden" id="{{coord}}Y" name="{{coord}}Y" value={{value[1]}}>
      {%- endfor %}
    </form>
    <input type="submit" value="Cancel" onclick="window.location.href='/';">
    <input type="submit" id="submitButton" form="court_coordinates" value="Submit All Points">
    <input type="hidden" id="image_path" value="{{image_path}}">
  </div>
  <div class="calibration_controls">
    <div>
      <input type="button" value="&#x21A5;" onclick="move_up()">
      <input type="button" value="&#x21A7;" onclick="move_down()">
      <input type="button" value="&#x21A4;" onclick="move_left()">
      <input type="button" value="&#x21A6;" onclick="move_right()">
      <!-- the 270 width of the current pixel & 462 width of the current point label were set by experiment (font size=40)-->
      <p id="current_x" style="min-width:150px;"></p>
      <p id="current_y" style="min-width:120px;"></p>
      <hr style="height:2px;margin-top:2px;margin-bottom:2px">
      <p id="current_point_label" style="min-width:462px;"></p>
      <input type="button" id="setButton" value="Prev" onclick="goToPoint(-1)">
      <input type="button" id="skipButton" value="Next" onclick="goToPoint(1)">
    </div>
  </div>
</div>
{%- endblock %}

{%- block page_specific_styles %} 
   <link rel="stylesheet" href="/static/css/cam-calib.css">
{%- endblock %} 

{%- block page_specific_js %} 
  <script src="/static/js/cam_calib.js" defer></script>
{%- endblock %} 

app/templates/layouts/cam_location.html
{% extends "layouts/base.html" %}

{%- block selections %}
<p class="para-nomargin">Measure 'A' from camera plumb bob to the left doubles corner.<br>'B' is from camera plumb bob to the right doubles corner.</p>
<form method="post" action="{{ url_for('blueprint_camera.cam_calib') }}">
  <div> 
    <table>
        <colgroup>
        <col span="1" style="width: 130px;">
        <col span="3" style="width: 360px;">
      </colgroup>
      <tr><td></td><td>Feet</td><td>Inches</td><td>Quarters</td></tr>
      {% for key,item in options.items() %}
        {%- if (item['start_div'] != null) %}<tr><td>{{item['start_div']}}</td>{% endif %}
        <td class="stepper">
          <!-- <label for="{{key}}">{{item['legend']}}:</label> -->
          <button type="button">–</button>
            <input type="number" id="{{key}}-stepper" name="{{key}}" value={{item['dflt']}} min={{item['min']}} max={{item['max']}} step={{item['step']}} readonly>
          <button type="button">+</button>
        </td>
        {%- if (item['end_div'] == "Y") %}</tr>{%- endif %}
      {%- endfor %}
    </table>
  <button type="submit" class="submit-button">Submit</button>
  </div>
</form>
{%- endblock %}

{%- block page_specific_styles %} 
  <link rel="stylesheet" href="/static/css/number-picker-2.css">
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      table-layout: fixed;
      /* width:1240px */
    }
    td, th {
      border: 1px solid #dddddd;
      /* text-align: left; */
      padding: 8px;
    }
    tr:nth-child(even) {
      background-color: #999999;
    }
  </style>
{%- endblock %} 

{%- block page_specific_js %} 
  <script src="/static/js/number-picker-2.js" defer></script>
{%- endblock %} 

app/templates/layouts/cam_position.html
{% extends "layouts/base.html" %}

{%- block selections %}
<p> Camera position: Measure 'A' from camera plumb bob mark to the left doubles corner; 
  'B' is from camera plumb bob mark to the right doubles corner.</p>
<form method="post" action="{{ url_for('cam_calib') }}">
  <div class="selections-class"> 
<!-- 
    <fieldset  class="radio-slider-buttons">
      <label>Camera: </label>
      <input type="radio" id="left" name="cam_id" value="l" checked>
      <label for="left" >Left</label><br>
      <input type="radio" id="right" name="cam_id" value="r">
      <label for="right">Right</label><br>
    </fieldset>
     -->
    <table>
      <tr><td></td><td>Feet</td><td>Inches</td><td>Quarters</td></tr>
      {% for key,item in options.items() %}
        {%- if (item['start_div'] != null) %}<tr><td>{{item['start_div']}}</td>{% endif %}
        <td class="stepper">
          <!-- <label for="{{key}}">{{item['legend']}}:</label> -->
          <button type="button">–</button>
            <input type="number" id="{{key}}-stepper" name="{{key}}" value={{item['dflt']}} min={{item['min']}} max={{item['max']}} step={{item['step']}} readonly>
          <button type="button">+</button>
        </td>
        {%- if (item['end_div'] == "Y") %}</tr>{%- endif %}
      {%- endfor %}
    </table>
  <button type="submit" class="submit-button">Submit</button>
  </div>
</form>

<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  tr:nth-child(even) {
    background-color: #999999;
  }
</style>
{% endblock %}

{% block page_specific_js %} 
<script src="/static/js/number-picker-2.js"></script>
{% endblock %} 

app/templates/layouts/cam_verif.html
{% extends "layouts/base.html" %}

{%- block selections %}
<div class="img-zoom-container">
  <div id="div_not_zoomed" class="div_not_zoomed_class">
    <canvas id="canvas_not_zoomed"></canvas>
  </div>
  <div style="width:220px; display: inline-block;">
    <form method="post" action="{{ url_for('blueprint_camera.cam_verif') }}">
      <input type="hidden" name="image_path" id="image_path" value="{{image_path}}">
      <button type="submit" class="submit-button">Other Side</button>
    </form>
    <button type="button" class="submit-button" onclick="refreshImage('even')">Reload Even</button>
    <button type="button" class="submit-button" onclick="refreshImage('odd')">Reload Odd</button>
    <button type="submit" onclick="window.location.href='/';" class="submit-button">Done</button>
    {%- for coord, value in court_point_coords.items() %}
    <input type="hidden" id="{{coord}}X" name="{{coord}}X" value={{value[0]}}>
    <input type="hidden" id="{{coord}}Y" name="{{coord}}Y" value={{value[1]}}>
    {%- endfor %}
  </div>
</div>
{%- endblock %}

{%- block page_specific_styles %} 
   <link rel="stylesheet" href="/static/css/cam-calib.css">
{%- endblock %} 

{%- block page_specific_js %} 
  <script src="/static/js/cam_calib.js" defer></script>
{%- endblock %} 

app/templates/layouts/drill.html
{% extends "layouts/base.html" %}

{%- block stats %} 
<div class="statistics-display">
  <br>
</div>
{%- endblock %}

{%- block selections %}
<div class="selections_45percent">
  {% for key,item in stepper_options.items() %}
  <div class="stepper">
    <label for="{{key}}">{{item['legend']}}:</label>
    <button type="button">–</button>
      <input type="number" id="{{key}}-stepper" name="{{key}}" value={{item['dflt']}} min={{item['min']}} max={{item['max']}} step={{item['step']}} readonly>
    <button type="button">+</button>
  </div>
  {% endfor %}

  {%- if radio_options is defined %}
    <br>
    {%- for fieldset in radio_options %}
    <fieldset class="radio-slider-buttons" id="{{fieldset['name']}}">
      <legend>{{fieldset['legend']}}:</legend>
        {%- for button in fieldset['buttons'] %}
        <input type="radio" id="{{fieldset['name']}}_{{button['label']}}" name="{{fieldset['name']}}" value={{button['value']}}
          {%- if button['checked'] is defined %} checked{%- endif %}>
        <label for="{{fieldset['name']}}_{{button['label']}}">{{button['label']}}</label>
        {%- endfor %}
    </fieldset>
    {%- endfor %}
  {%- endif %}
</div>

{%- endblock %}

{%- block control %}
<div class="start-stop">
  <button type="button" id="pause-resume" class="pause-resume-button resume">
  </button>
  <button type="submit" onclick="window.location.href='{{ url_for('blueprint_core.done') }}';">
    <img src="/static/stop.png">
  </button>
</div>
{%- endblock %}

{%- block page_specific_styles %} 
  <link rel="stylesheet" href="/static/css/number-picker-2.css">
  <link rel="stylesheet" href="/static/css/radio-slider.css">
{%- endblock %} 

{%- block page_specific_js %} 
  <script src="/static/js/pause_resume.js" defer></script>
  <script src="/static/js/number-picker-2.js" defer ></script>
  <script src="/static/js/radio-button-emit.js" defer ></script>
{%- endblock %} 

app/templates/layouts/drill_select_filtered.html
{% extends "layouts/base.html" %}

<!--  the minus sigh after the <% below keeps ninja2 from emitting a newline   -->
{% block selections %}
<div class="selections-drill">
  <div id="placeHolder"> </div>
  <fieldset id="container" class="radio-text-buttons">
    {%- for drill in drills %}
      {%- if filters|length > 0 %}
    <input type="radio" id="{{drill['id']}}" name="drill_id" value="{{drill['id']}}" 
      {% for filter in filters %}{{filter}}="{{drill['filter_values'][loop.index-1]}}"{% endfor %}>
    <label for="{{drill['id']}}" {% for filter in filters %}{{filter}}="{{drill['filter_values'][loop.index-1]}}"{% endfor %}
      >{{drill['name']}}</label>
      {%- else %}
    <input type="radio" id="{{drill['id']}}" name="drill_id" value="{{drill['id']}}">
    <label for="{{drill['id']}}">{{drill['name']}}</label>
      {%- endif %}
    {% endfor %}
  </fieldset>
</div>
{% endblock %}

{% block control %}
  <div class="start-stop">
    <button type="submit">
      <img src="/static/start.png">
    </button>
  </div>
{% endblock %}

app/templates/layouts/drill_select_player.html
{% extends "layouts/base.html" %}

{% block selections %}
<div class="selections-drill">
  <div id="placeHolder"> </div>
  <fieldset id="container" class="radio-text-buttons">
    {% for drill in drills %}
    <input type="radio" id="{{drill['id']}}" name="drill_id" value="{{drill['id']}}" 
      data-Type="{{drill['type']}}" data-Stroke="{{drill['stroke']}}" data-Difficulty="{{drill['difficulty']}}">
    <label for="{{drill['id']}}" data-Type="{{drill['type']}}" data-Stroke="{{drill['stroke']}}"
      data-Difficulty="{{drill['difficulty']}}">{{drill['name']}}</label>
    {% endfor %}
  </fieldset>
</div>

<!-- 
<div class="selections">
  <div id="placeHolder"> </div>
  <fieldset id="container" class="radio-text-buttons">
    <input type="radio" id="DRL001" name="drill_id" value="DRL001" data-Type="speed">
    <label for="DRL001" data-Type="speed">speed test</label>
    <input type="radio" id="DRL002" name="drill_id" value="DRL002" data-Type="groundstroke">
    <label for="DRL002" data-Type="groundstroke">2-line groundstroke footwork</label>
    <input type="radio" id="DRL003" name="drill_id" value="DRL003" data-Type="suicide">
    <label for="DRL003" data-Type="suicide">2-line suicide</label>
  </fieldset>
</div>
 -->

{% endblock %}

{% block control %}
  <div class="start-stop">
    <button type="submit">
      <img src="/static/start.png">
    </button>
  </div>
{% endblock %}

{% block page_specific_js %} 
<script src="/static/js/jquery-1.7.1.min.js"></script>
<!-- <script src="/static/js/filtrify.min.js"></script> -->
<script src="/static/js/b_filtrify.js"></script>
<!-- 
<script src="/static/js/highlight.pack.js"></script>
<script src="/static/js/script.js"></script>
 -->
<script type="text/javascript">
  $(function() {
    $.filtrify("container", "placeHolder");
  });
</script>    
<link rel="stylesheet" href="/static/css/b_filtrify.css">

{% endblock %} 

app/templates/layouts/drill_select_test.html
{% extends "layouts/base.html" %}

{% block selections %}
<!-- drills = { "001": {"name": "speed", "type":"movement", "lvl": "medium", "stroke": "forehand" } -->

<div class="selections-drill">
  <div id="placeHolder"> </div>
  <fieldset id="container" class="radio-text-buttons">
    {% for drill in drills %}
    <input type="radio" id="{{drill['id']}}" name="drill_id" value="{{drill['id']}}">
    <label for="{{drill['id']}}">{{drill['name']}}</label>
    {% endfor %}
  </fieldset>
</div>

{% endblock %}

{% block control %}
  <div class="start-stop">
    <button type="submit">
      <img src="/static/start.png">
    </button>
  </div>
{% endblock %}

{% block page_specific_js %} 

{% endblock %} 

app/templates/layouts/game.html
{% extends "layouts/base.html" %}

{%- block stats %} 
<div class="statistics-display">
  <p class="para-nomargin" id="server">TBD's serve</p>
  <div class="Table">
    <!-- <div class="Title">
      <p>Game Score</p>
    </div> -->
    <div class="Heading">
      <div class="Col1Row1Cell">
        <p></p>
      </div>
      <div class="Cell">
        <p>Set</p>
      </div>
      <div class="Cell">
        <p>Game</p>
      </div>
      <div class="Cell">
        <p>Points</p>
      </div>
      <div class="Cell">
        <p>Tie Points</p>
      </div>
    </div>
    <div class="Row">
      <div class="Col1Cell">
        <p>Boomer</p>
      </div>
      <div class="Cell">
        <p id="b_sets">0</p>
      </div>
      <div class="Cell">
        <p id="b_games">0</p>
      </div>
      <div class="Cell">
        <p id="b_pts">0</p>
      </div>
      <div class="Cell">
        <p id="b_t_pts">0</p>
      </div>
    </div>
    <div class="Row">
      <div class="Col1Cell">
        <p>Player</p>
      </div>
      <div class="Cell">
        <p id="p_sets">0</p>
      </div>
      <div class="Cell">
        <p id="p_games">0</p>
      </div>
      <div class="Cell">
        <p id="p_pts">0</p>
      </div>
      <div class="Cell">
        <p id="p_t_pts">0</p>
      </div>
    </div>
  </div>
</div>
{%- endblock %} 

{%- block selections %}
<div class="selections_45percent">
  <div class="stepper">
    <label for="level">Level:</label>
    <button type="button">–</button>
    <input type="number" id="level-stepper" name="level" value={{level_dflt}} min={{level_min}} max={{level_max}} step={{level_step}} readonly>
    <button type="button">+</button>
  </div>
</div>
{%- endblock %}

{%- block control %}
<div class="start-stop">
  <button type="button" id="pause-resume" class="pause-resume-button resume">
  </button>
  <button type="submit" class="start-stop.stop" onclick="window.location.href='{{ url_for('blueprint_core.done') }}';">
    <img src="/static/stop.png">
  </button>
  <br>
  <br>
  <button type="button" id="game_help_button">
    <img src="/static/help.png">
  </button>
</div>
{%- endblock %}

{%- block page_specific_styles %} 
  <link rel="stylesheet" href="/static/css/tables.css">
  <link rel="stylesheet" href="/static/css/number-picker-2.css">
{%- endblock %} 

{%- block page_specific_js %} 
  <script src="/static/js/number-picker-2.js" defer ></script>
  <script src="/static/js/pause_resume.js" defer></script>
  <script src="/static/js/game_help.js" defer></script>
{%- endblock %} 